services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/uploads
    env_file:
      - ./analyzer/.env
    environment:
      - ANALYZER_API_BASEURL=http://analyzer:8001/api/v1
    depends_on:
      - postgres
      - analyzer
    networks:
      - smartclause_network

  analyzer:
    build: ./analyzer
    # Development access - localhost only, secure for deployment
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ./analyzer:/app
      - ./datasets:/datasets
    env_file:
      - ./analyzer/.env
    depends_on:
      - postgres
    networks:
      - smartclause_network

  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - ./analyzer/.env
    # Remove external port binding - only accessible internally
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./analyzer/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smartclause_network

  chat:
    build: ./chat
    # Development access - localhost only, secure for deployment
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ./chat:/app
    env_file:
      - ./chat/.env
    environment:
      - ANALYZER_BASE_URL=http://analyzer:8001/api/v1
    depends_on:
      - postgres
      - analyzer
    networks:
      - smartclause_network

  frontend:
    build: ./frontend
    command: npm run serve
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - analyzer
      - chat
    networks:
      - smartclause_network

networks:
  smartclause_network:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  backend_uploads: 