services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/uploads
    env_file:
      - ./analyzer/.env
    environment:
      - ANALYZER_API_BASEURL=http://analyzer:8001/api/v1
    depends_on:
      - postgres
      - analyzer

  analyzer:
    build: ./analyzer
    ports:
      - "8001:8001"
    volumes:
      - ./analyzer:/app
    env_file:
      - ./analyzer/.env
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - ./analyzer/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./analyzer/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - analyzer

volumes:
  postgres_data:
  backend_uploads: 